markdown: rdiscount
pygments: true
paginate: 10
paginate_path: "blog/page:num"
permalink: /blog/:year/:month/:day/:title
rdiscount:
  extensions: [smart]
exclude: [ Gemfile, Gemfile.lock, gems, _assets, bower_components ]
title : Ben Newton - Front End Engineer
production_url : http://benenewton.com
description: "Ben Newton - Front End Engineer"
disqus_shortname: bensbrain
analytics:
tagmanager: GTM-NDWX5Q
gauges:
author :
  name : Ben Newton
  github : bennewton999
  twitter : BenENewton
  email: bennewton999@gmail.com
